##########################################
#                                        #
#            INVENTORY SYNCER            #
#                                        #
##########################################

#SQL Configuration
sqlCredentials:
  #Your host ex: XXX.XX.XXX.XX
  host: yourhost
  #The port toi connect to databse, often is 3306
  port: portofyourdb
  #User for the connexion
  user: yourusername
  #Password for the connexion
  password: dbpassword
  #Name of the database
  dbName: nameofyourdb

